apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-publisher
  namespace: {{ .Release.Namespace }}
  labels:
    app: event-publisher
spec:
  replicas: {{ .Values.eventPublisher.replicaCount }}
  selector:
    matchLabels:
      app: event-publisher
  template:
    metadata:
      labels:
        app: event-publisher
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
      - name: event-publisher
        image: "{{ .Values.global.registry }}/{{ .Values.eventPublisher.image.repository }}:{{ .Values.eventPublisher.image.tag }}"
        imagePullPolicy: {{ .Values.eventPublisher.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8084
          name: esl-socket
        env:
        - name: LEAD_SERVICE_URL
          value: {{ .Values.eventPublisher.leadServiceUrl | quote }}
        - name: LEAD_SERVICE_MAX_RETRIES
          value: {{ .Values.eventPublisher.maxRetries | quote }}
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
        resources:
          {{- toYaml .Values.eventPublisher.resources | nindent 10 }}
