apiVersion: apps/v1
kind: Deployment
metadata:
  name: lead-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: lead-service
spec:
  replicas: {{ .Values.leadService.replicaCount }}
  selector:
    matchLabels:
      app: lead-service
  template:
    metadata:
      labels:
        app: lead-service
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
      - name: lead-service
        image: "{{ .Values.global.registry }}/{{ .Values.leadService.image.repository }}:{{ .Values.leadService.image.tag }}"
        imagePullPolicy: {{ .Values.leadService.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DB_URL
          value: {{ .Values.leadService.dbUrl | quote }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: AMI_ENABLED
          value: "false"
        - name: LEAD_CONTEXT
          value: {{ .Values.leadService.leadContext | quote }}
        - name: LEAD_REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              name: lead-registry-config
              key: LEAD_REGISTRY_URL
        - name: LEAD_REGISTRY_API_KEY_HEADER
          valueFrom:
            configMapKeyRef:
              name: lead-registry-config
              key: LEAD_REGISTRY_API_KEY_HEADER
        - name: LEAD_REGISTRY_API_KEY_VALUE
          valueFrom:
            configMapKeyRef:
              name: lead-registry-config
              key: LEAD_REGISTRY_API_KEY_VALUE
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
        resources:
          {{- toYaml .Values.leadService.resources | nindent 10 }}
