apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  pgadmin-email: {{ .Values.pgadmin.email | b64enc | quote }}
  pgadmin-password: {{ required "A valid pgadmin.password is required" .Values.pgadmin.password | b64enc | quote }}
