apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgres-user: {{ .Values.postgres.user | b64enc | quote }}
  postgres-password: {{ required "A valid postgres.password is required" .Values.postgres.password | b64enc | quote }}
